<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Build -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet -->
    <PackageId>AvaloniaGauge</PackageId>
    <Authors>Alfred Hunt</Authors>
    <Description>A customizable, resizable gauge control for Avalonia UI applications.</Description>
    <PackageTags>avalonia;avaloniaui;gauge;control;dotnet</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Repository -->
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/alfredhunt/AvaloniaGauge</RepositoryUrl>
  </PropertyGroup>

  <!-- Avalonia default control theme -->
  <ItemGroup>
    <AvaloniaXaml Remove="Themes\Generic.axaml" />
    <AvaloniaResource Include="Themes\Generic.axaml" />
  </ItemGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.1" />
  </ItemGroup>

  <!-- NuGet package contents -->
  <ItemGroup>
    <None Include="..\..\README.md"
          Pack="true"
          PackagePath="\" />
  </ItemGroup>

</Project>